# Generated by Django 3.2.5 on 2021-08-04 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='premierLeagueTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=24, verbose_name='player_id')),
                ('player_name', models.CharField(max_length=50, verbose_name='player_name')),
                ('games', models.CharField(max_length=10, verbose_name='games')),
                ('time', models.CharField(max_length=10, verbose_name='time')),
                ('goals', models.CharField(max_length=10, verbose_name='goals')),
                ('xG', models.CharField(max_length=50, verbose_name='xG')),
                ('assists', models.CharField(max_length=50, verbose_name='assists')),
                ('xA', models.CharField(max_length=50, verbose_name='xA')),
                ('shots', models.CharField(max_length=50, verbose_name='shots')),
                ('key_passes', models.CharField(max_length=50, verbose_name='key_passes')),
                ('yellow_cards', models.CharField(max_length=10, verbose_name='yellow_cards')),
                ('red_cards', models.CharField(max_length=10, verbose_name='red_cards')),
                ('position', models.CharField(max_length=10, verbose_name='position')),
                ('team_title', models.CharField(max_length=50, verbose_name='team_title')),
                ('npg', models.CharField(max_length=10, verbose_name='npg')),
                ('npxG', models.CharField(max_length=50, verbose_name='npxG')),
                ('xGChain', models.CharField(max_length=50, verbose_name='xGChain')),
                ('xGBuildup', models.CharField(max_length=50, verbose_name='xGBuildup')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
