# Generated by Django 3.2.5 on 2021-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laLigaTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('country', models.CharField(default='Spain', max_length=20, verbose_name='Country')),
                ('shortCode', models.CharField(max_length=10, verbose_name='Short Code')),
                ('logo', models.URLField(max_length=240, verbose_name='Logo')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
